FROM ubuntu:latest

# UPDATE
RUN apt-get update
RUN apt-get upgrade

# MAKE NON INTERACTIVE
ENV DEBIAN_FRONTEND=noninteractive

# INSTALL APTITUDE & GIT
RUN apt-get install aptitude -y
RUN apt-get install git -y

# INSTALL REQUIRED DEPENDENCIES
RUN apt-get install -y libmicrohttpd-dev libjansson-dev libssl-dev libsrtp2-dev libsofia-sip-ua-dev libglib2.0-dev libopus-dev libogg-dev libcurl4-openssl-dev liblua5.3-dev libconfig-dev pkg-config gengetopt libtool automake

# INSTALL EXTRA DEPENDENCIES
RUN apt-get install doxygen graphviz -y

# INSTALL PYTHON DEPS FOR LIBNICE
RUN apt-get install python3-pip -y
RUN pip3 install meson ninja

# INSTALL LIBNICE
RUN git clone https://gitlab.freedesktop.org/libnice/libnice
RUN cd libnice && meson --prefix=/usr build && ninja -C build && ninja -C build install

# FETCH JANUS
RUN git clone https://github.com/meetecho/janus-gateway.git
WORKDIR janus-gateway
RUN sh autogen.sh

# INSTALL & CONFIGURE JANUS
RUN ./configure --prefix=/opt/janus
RUN make
RUN make install
RUN make configs
RUN ./configure --enable-docs

# LAUNCH
CMD ["/opt/janus/bin/janus"]